import { Interiors } from "./Interiors.js"
import { Paints } from "./Paints.js"
import { Orders } from "./Orders.js"
import { Wheels } from "./Wheels.js"
import { Technologies } from "./Technologies.js"